### ISSUE TITLE
Task 1: Develop direction document

### ISSUE THREAD

**Issue by smit1678** [hotosm/projects#13]
We will develop a direction document that captures research, reviews options, pros/cons, and provides recommendations forward with potential architecture.

**Comment by russbiggs** [comment]
Direction document:
https://docs.google.com/document/d/16Q8TJbI4j1NLyy3ng8r12u4kOKNHXhyBoGr0yv-eQGU/edit?usp=sharing

**Comment by russbiggs** [comment]
@smit1678 I've updated the document with some additional points raised during Monday's call.

**Comment by smit1678** [comment]
Looks good @russbiggs. Can you write up your plan of attack in https://github.com/hotosm/projects/issues/14? Add any items to the backlog for me if needed (like create a repo if you want me to do that). 

To add a few more notes for documentation purposes here: 

* we held a meeting on March 18 to review the direction document
* We agreed upon the direction of a static site generator like Hugo as a good direction for giving flexibility
* We dug into some more detailed discussions plus need for some additional research around: 
  - search
  - image sizing / loading for low-bandwidth environments
  - LaTeX and other type support
* Research on these items will feed in to the MVP during Sprint 1
