### ISSUE TITLE
Sprint 1: MVP of documentation site

### ISSUE THREAD

**Issue by smit1678** [hotosm/projects#14]
Develop initial working version with content from Toolbox or Refugee Mapping Toolbox to test ideas and review.

**Comment by russbiggs** [comment]
### Workplan

* Experiment with Hugo templates and features based on 3/18 meeting _in progress_
* Research for additional topics from 3/18 meeting (search, image processing pdf generation) _in progress_
* Develop MVP with hotosm/toolbox wiki content
* Begin documentation of lessons learned from initial development

Items needed from @smit1678 : 
* Edit permissions to https://github.com/hotosm/toolbox wiki markdown for development 
* github repo for toolkit site
* github repo for template edits (I've init'ed a git submodule so I can VC any customizations) maybe named hotosm-hugo-book or similar?

**Comment by smit1678** [comment]
> Edit permissions to https://github.com/hotosm/toolbox/wiki markdown for development

done, https://github.com/hotosm/toolbox/invitations

> github repo for toolkit site

done, https://github.com/hotosm/toolkit-site

> github repo for template edits (I've init'ed a git submodule so I can VC any customizations) maybe named hotosm-hugo-book or similar?

done, https://github.com/hotosm/hugo-book. can we give it a catchy name? :)

**Comment by russbiggs** [comment]
I've pushed the base template to https://github.com/hotosm/hugo-book. I'm wondering if we should just do a proper github fork in the HOT organization. Not sure if there is any benefit one way or another. Any thoughts @smit1678?

**Comment by russbiggs** [comment]
@smit1678 Can you set up a github repo for the base platform template (to hold hugo structure, CI config, README with how-tos etc.) Maybe named 'hot-docs-template'

**Comment by smit1678** [comment]
@russbiggs Done ✅ https://github.com/hotosm/hot-docs-template

**Comment by russbiggs** [comment]
MVP is up here:

https://hotosm.github.io/toolkit-site/docs/

The routing is still a bit funny on gh-pages and it requires a bit of git fancy footwork. These can be ironed out in the upcoming sprint.
