### ISSUE TITLE
Sprint 2: Design, deployment, PDF additions

### ISSUE THREAD

**Issue by smit1678** [hotosm/projects#15]
Sprint 2 will focus on adding any HOT design (if and where applicable and based on direction), testing deployment options, and optimizing PDF generation.

**Comment by russbiggs** [comment]
The game plan for this sprint is as follows:
### week 1:
* rework hugo-book to HOT style guide
   * add nav bar
   * add footer
   * style as needed for HOT branding
* rework hugo-book to remove /docs sub folder 
   * allows for better root level content generation
   * provides more flexibility for i18n down the road
### week 2
* PDF generation tooling
* circleci integration
* lunr search integration

**Comment by russbiggs** [comment]
Sprint 2 completed:

* Reworked hugo-book theme to work with both hugo language methods
* added HOT branding and reworked overall layout to include header and footer with HOT info
* Tested pandoc for PDF generation (seeking more feedback in sprint 3)
* lunr integration was put off until sprint 3
