### ISSUE TITLE
Sprint 3: Documentation and feedback

### ISSUE THREAD

**Issue by smit1678** [hotosm/projects#16]
Sprint 3 will be the final sprint focused on documentation (contributing, deployment, how new sites are created) and implementing any feedback on final design and deployment process.

**Comment by russbiggs** [comment]
Initial Plan for Sprint 3:

* Finalize HOT branding
* Mobile layout fixes
* PDF build process
* CircleCI setup and testing
* lunr search integration and build process
* HOT Docs Template readme documentation (week 2)

**Comment by russbiggs** [comment]
I have a working prototype of the circleci functionality running. Currently can build hugo site, create PDFs and deploy to gh-page branch. Some details TBD this week @smit1678  on github deployment.

**Comment by russbiggs** [comment]
Toolkit site is up and running with circleCI handling the pdf processing and deployment to github pages. The pdf processing may have issues with deeply nested content structures particularly in maintaining their order for the bundled site pdf. This will be more defined in the hot-docs-template repo readme for explanations of best practices.
