### ISSUE TITLE
Generating content: Open Mapping for SGDs Guide

### ISSUE THREAD

**Issue by smit1678** [hotosm/projects#27]
As a part of the documentation site work, we need to be moving content from the PDF on http://www.data4sdgs.org/resources/open-mapping-sdgs to markdown on a Github repository. 

@PaulUithol @jessbeutler and Sara -- has work already progressed on this front? 

If not, I'd like to outline some next steps for getting that content on Github so that it can then be integrated for testing soon with @russbiggs.

**Comment by saraamadi** [comment]
Hi @smit1678 - thanks for this. I am now on Github! As @jessbeutler mentioned, we'll be working on content generation early next week. Happy to chat then (or even before) about putting some of this content onto Github for testing purposes.

**Comment by smit1678** [comment]
Great, thanks @saraamadi. Welcome to Github! :) Let me know if you and @jessbeutler want to have a new repo to start to drop in documents that get drafted.

**Comment by smit1678** [comment]
GPSDD content online and available: https://github.com/hotosm/gpsdd-documentation. Link to live site here: https://hotosm.github.io/gpsdd-documentation/
