### ISSUE TITLE
Generating content: Toolkit organization

### ISSUE THREAD

**Issue by smit1678** [hotosm/projects#47]
The HOT Toolkit documentation is being used as the primary content use case for this first phase of work on the documentation site. To round out this first phase, we need to come up with a menu structure to help model and test how the menu functionality works. 

Currently we've mocked it up with a chapter organization: 

<img width="835" alt="HOT Toolbox 2019-04-29 10-25-43" src="https://user-images.githubusercontent.com/796838/56875168-35e7ba00-6a69-11e9-91fa-df76d5aec88b.png">

@jessbeutler Let's tackle a couple items by Wednesday (these are the open questions I have for how we get this to a completed state to circulate wider): 

- [ ] Outline a structure with titles that make sense. I don't think Chapters is the right language here and I'm sure that you've thought out the structure and naming a little bit
- [ ] Check if titles work. @jessbeutler do you like the numbers in front of each page title? 
- [ ] Rework new structure into toolkit-site repo content https://github.com/hotosm/toolkit-site/tree/master/content/pages

**Comment by jessbeutler** [comment]
@smit1678 @russbiggs Each "chapter" already have titles here: https://github.com/hotosm/toolbox/wiki
i.e. Chapter 1 should be "Running a Mapping Project"

I'm personally okay removing the numbering as not every workflow will follow a particular order. However, those were originally set up by @PaulUithol so I'll defer to his opinion on that.

**Comment by russbiggs** [comment]
I can swap out the “chapter 1,2 etc” for these titles this morning currently the numbering is causing the sorting but if we want to remove it we can also indicate sort in the md frontmatter

**Comment by smit1678** [comment]
Closing this since the first round of development has been completed.
